In [14]:
import numpy as np

In [15]:
X = np.array([[  1, 677],
 [  1, 678],
 [  1, 676],
 [  1, 677],
 [  1, 675]])
y = np.array([1150,  942,  839,  735,  631])
P = X.T@X
print(P, np.linalg.matrix_rank(P))
P_inv = np.linalg.inv(P)
print(P_inv)
P2 = P_inv@X.T
print(P2)
w = P2@y
print(w)

[[      5    3383]
 [   3383 2288943]] 2
[[ 8.80362692e+04 -1.30115385e+02]
 [-1.30115385e+02  1.92307692e-01]]
[[-5.18461538e+01 -1.81961538e+02  7.82692308e+01 -5.18461538e+01
   2.08384615e+02]
 [ 7.69230769e-02  2.69230769e-01 -1.15384615e-01  7.69230769e-02
  -3.07692308e-01]]
[-71979.19230576    107.65384615]


In [23]:
X = np.array([[  1, 360],
 [  1, 357],
 [  1, 360]])
y = np.array([632, 735, 835])
P = X.T@X
print(P, np.linalg.matrix_rank(P))
P_inv = np.linalg.inv(P)
# P_inv = np.linalg.pinv(P)
print(P_inv)
P2 = P_inv@X.T
print(P2)
w = P2@y.T
print(w)

[[     3   1077]
 [  1077 386649]] 2
[[ 2.14805000e+04 -5.98333333e+01]
 [-5.98333333e+01  1.66666667e-01]]
[[-59.5        120.         -59.5       ]
 [  0.16666667  -0.33333333   0.16666667]]
[ 9.135e+02 -5.000e-01]


In [1]:
board = [
        [-4, -2, -3, -5, -6, -3, -2, -4],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [4, 2, 3, 5, 6, 3, 2, 4],
    ][::-1]
print(board)


[[4, 2, 3, 5, 6, 3, 2, 4], [1, 1, 1, 1, 1, 1, 1, 1], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [-1, -1, -1, -1, -1, -1, -1, -1], [-4, -2, -3, -5, -6, -3, -2, -4]]


In [ ]:
from utils import *
from config import *
import copy
video = load_video(f".{VIDEOS_DIR}/test_video2.mp4")
for i, frame in enumerate(video):
    # Show the frame
    cv2.imshow('Video', frame)
    # Wait for the key
    key = cv2.waitKey(0)
    # If the key is 'n' continue to the next frame
    if key == ord('n'):
        continue
    # If the key is 's' select the frame as the reference frame
    elif key == ord('s'):
        # Copy the frame to use it as a reference
        reference_frame = copy.deepcopy(frame)
        # Convert the reference frame to grayscale
        # reference_frame = cv2.cvtColor(reference_frame, cv2.COLOR_BGR2GRAY)
        print('Frame {} selected as reference frame'.format(i))
        break

get_hsv_color_ranges(reference_frame)


../data/other_data/videos/test_video2.mp4
Frame 50 selected as reference frame
(hMin = 0 , sMin = 0, vMin = 0), (hMax = 255 , sMax = 255, vMax = 255)
(hMin = 0 , sMin = 0, vMin = 10), (hMax = 255 , sMax = 255, vMax = 255)
(hMin = 0 , sMin = 0, vMin = 18), (hMax = 255 , sMax = 255, vMax = 255)
(hMin = 0 , sMin = 0, vMin = 26), (hMax = 255 , sMax = 255, vMax = 255)
(hMin = 0 , sMin = 0, vMin = 45), (hMax = 255 , sMax = 255, vMax = 255)
(hMin = 0 , sMin = 0, vMin = 52), (hMax = 255 , sMax = 255, vMax = 255)
(hMin = 0 , sMin = 0, vMin = 65), (hMax = 255 , sMax = 255, vMax = 255)
(hMin = 0 , sMin = 0, vMin = 76), (hMax = 255 , sMax = 255, vMax = 255)
(hMin = 0 , sMin = 0, vMin = 71), (hMax = 255 , sMax = 255, vMax = 255)
(hMin = 0 , sMin = 0, vMin = 63), (hMax = 255 , sMax = 255, vMax = 255)
(hMin = 0 , sMin = 0, vMin = 50), (hMax = 255 , sMax = 255, vMax = 255)
(hMin = 0 , sMin = 0, vMin = 45), (hMax = 255 , sMax = 255, vMax = 255)
(hMin = 0 , sMin = 0, vMin = 37), (hMax = 255 , sMax = 255